### ISSUE TITLE
Add "Open all/Close all" button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#47]
@wsalesky I anticipate that some people may grow tired of opening all the collapsibles by hand. To makes things a bit easier for them, it would be great if you could add a button that opens all collapsibles at once. This button would be called "Open all". 
![Screenshot 2023-09-25 at 19-51-27 London British Library Oriental 2523 1](https://github.com/majlis-erc/srophe/assets/73166992/1b4a7cf6-6e2c-4b6e-a96b-b349ce596eed)

The button should alternate between opening and closing collapsibles – taking into account that users may open and close collapsibles by hand at random.

**Comment by wsalesky** [comment]
Resolved by: https://github.com/majlis-erc/srophe/pull/51

**Comment by mMoliere** [comment]
@wsalesky I'm afraid, I still can't see the button despite emptying my cache several times.
